api/urls.py
from django.urls import path, include

urlpatterns = [
    path('v1/', include('api.v1.urls'))
]

api/v1/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *


router = routers.DefaultRouter()

router.register(r'board', BoardViewset)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

board/urls.py
from django.urls import path
from .views import *


app_name = 'board'

urlpatterns = [
    path('', index, name="index"),
    path('board/', board_list, name="list"),
    path('board/<int:pk>', board_detail, name="detail"),
    path('board/create', board_create, name='create'),
    path('board/update/<int:pk>', board_update, name='update'),
    path('board/delete/<int:pk>', board_delete, name='delete'),
]

board_auth_web_api_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('', include('board_class.urls')),
    path('api/', include('api.urls'))
]

board_class/urls.py
from django.urls import path
from .views import *


app_name = 'board_class'

urlpatterns = [
    path('board_class/', Index.as_view(), name="index"),
    path('board_class/list', BoardList.as_view(), name="list"),
    path('board_class/<int:pk>', BoardDetail.as_view(), name="detail"),
    path('board_class/create', BoardCreate.as_view(), name='create'),
    path('board_class/update/<int:pk>', BoardUpdate.as_view(), name='update'),
    path('board_class/delete/<int:pk>', BoardDelete.as_view(), name='delete'),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Board(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True)


class Reply(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    content = models.TextField()
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

board_class/models.py
from django.db import models

# Create your models here.

board_class/forms.py
from django import forms
from board.models import Board


class BoardForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ['title', 'content', 'user']

api/v1/views.py
from rest_framework import response, viewsets, permissions
from board.models import *
from api.serializers.boardSerializer import *


class BoardViewset(viewsets.ModelViewSet):
    queryset = Board.objects.all()
    serializer_class = BoardSerializer
    # permission_classes = ['AllowAny']

    def perform_create(self, serializer):
        serializer.save(user=User.objects.get(id=1))

api/views.py
from django.shortcuts import render

# Create your views here.

board/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import *


# Create your views here.
def index(request):
    return render(request, 'index.html')


def board_list(request):
    boards = Board.objects.all()
    context = {
        'boards': boards
    }
    return render(request, 'board/list.html', context)


def board_detail(request, pk):
    board = get_object_or_404(Board, id=pk)
    context = {
        'board': board
    }
    return render(request, 'board/detail.html', context)


def board_create(request):


    if request.method == 'GET':
        return render(request, 'board/create.html')

    if request.method == 'POST':

        title = request.POST.get('title')
        content = request.POST.get('content')

        board = Board.objects.create(title=title, content=content, user_id=1)

        return redirect(f'/board/{board.id}')


def board_update(request, pk):

    if request.method == 'GET':
        board = get_object_or_404(Board, id=pk)
        context = {'board': board}
        return render(request, 'board/update.html', context)

    if request.method == 'POST':

        title = request.POST.get('title')
        content = request.POST.get('content')

        board = Board.objects.filter(id=pk).update(title=title, content=content)

        return redirect(f'/board/{pk}')


def board_delete(request, pk):

    Board.objects.filter(id=pk).delete()
    return redirect(f'/board/')

board_class/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy

from board.models import *
from django.views.generic import *
from .forms import BoardForm


class Index(TemplateView):
    template_name = 'board_class/index.html'


class BoardList(ListView):
    template_name = 'board_class/list.html'
    context_object_name = 'boards'

    '''
    추가 context 데이터가 필요 없는 경우
    get_queryset 방식으로 넘김
    '''
    # def get_queryset(self):
    #     boards = Board.objects.all()
    #     return boards

    '''
    get_context_data 방식으로 넘길때 모델 지정 필요
    context 에 추가 데이터 넣을 수 있음.
    '''
    model = Board

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context


class BoardDetail(DetailView):
    model = Board
    template_name = 'board_class/detail.html'


class BoardCreate(CreateView):
    model = Board
    form_class = BoardForm
    template_name = 'board_class/create.html'
    success_url = reverse_lazy('board_class:list')

    def form_valid(self, form):
        board_post = form.save(commit=False)
        user = User.objects.get(id=1)  # 임시
        board_post.user = user
        board_post.save()
        return super().form_valid(form)


class BoardUpdate(UpdateView):
    model = Board
    fields = ['title', 'content']
    template_name = 'board_class/update.html'

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse_lazy('board_class:detail', kwargs={'pk': pk})


class BoardDelete(DeleteView):
    model = Board
    success_url = reverse_lazy('board_class:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

board/templates/board/create.html
{% extends './base.html' %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>게시판 쓰기</legend>
        <div>
            <label for="title">제목:</label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="content">내용:</label>
            <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </div>
        <button type="submit">올리기</button>
    </fieldset>
    </form>

{% endblock %}

board/templates/board/detail.html
{% extends './base.html' %}

{% block content %}

    <h1>{{ board.title }}</h1>
    <hr/>
    <div>
    <pre>{{ board.content }}</pre>
    </div>


    <a href="{% url 'board:list' %}">목록</a>
    <a href="{% url 'board:update' board.id %}">수정하기</a>
    <a href="{% url 'board:delete' board.id %}">삭제하기</a>

{% endblock %}

board/templates/board/list.html
{% extends './base.html' %}

{% block content %}
    <ul>
    {% for board in boards %}
    <li><a href="{% url 'board:detail' board.id %}">{{ board.title }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

board_class/templates/board_class/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

board_class/templates/board_class/create.html
{% extends './base.html' %}

{% block content %}

    <form action="{% url 'board_class:create' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Board_class 게시판 쓰기</legend>
        <div>
            <label for="title">제목:</label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="content">내용:</label>
            <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </div>
        <button type="submit">올리기</button>
    </fieldset>
    </form>

{% endblock %}

board_class/templates/board_class/detail.html
{% extends './base.html' %}

{% block content %}

    <h1>{{ board.title }}</h1>
    <hr/>
    <div>
    <pre>{{ board.content }}</pre>
    </div>


    <a href="{% url 'board_class:list' %}">목록</a>
    <a href="{% url 'board_class:update' board.id %}">수정하기</a>
    <form action="{% url 'board_class:delete' board.id %}" method="post">
        {% csrf_token %}
        <button>삭제하기</button>
    </form>

{% endblock %}

board_class/templates/board_class/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Home</h1>
</body>
</html>

board_class/templates/board_class/list.html
{% extends './base.html' %}

{% block content %}
    <ul>
    {% for board in boards %}
    <li><a href="{% url 'board_class:detail' board.id %}">{{ board.title }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'board_class:create' %}">글쓰기</a>
{% endblock %}

board_class/templates/board_class/update.html
{% extends './base.html' %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>게시판 수정</legend>
        <div>
            <label for="title">제목:</label>
            <input type="text" name="title" id="title" value="{{ board.title }}">
        </div>
        <div>
            <label for="content">내용:</label>
            <textarea name="content" id="content" cols="30" rows="10">{{ board.content }}</textarea>
        </div>
        <button type="submit">수정하기</button>
    </fieldset>
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Title</title>
</head>
<body>

</body>
</html>